### ISSUE TITLE
Проблема с task 'watch'

### ISSUE THREAD

**Issue by suenot** [sergeylaptev/react-fundamentals#1]
Попробовал уже поставить пакет gaze с --save-dev, не помогло.

``` bash
suenot@suenot ~/sites/react-fundamentals (master)*$ gulp 
[11:20:31] Requiring external module coffee-script/register
[11:20:34] Using gulpfile ~/sites/react-fundamentals/gulpfile.coffee
[11:20:34] Starting 'setWatch'...
[11:20:34] Finished 'setWatch' after 141 μs
[11:20:34] Starting 'browserSync'...
[11:20:34] Finished 'browserSync' after 85 ms
[11:20:34] Starting 'watch'...
[11:20:34] 'watch' errored after 19 ms
[11:20:34] Error: watch ENOSPC
  at exports._errnoException (util.js:746:11)
  at FSWatcher.start (fs.js:1176:11)
  at Object.fs.watch (fs.js:1202:11)
  at Gaze._watchDir (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
  at /home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
  at Gulp.watch (/home/suenot/sites/react-fundamentals/node_modules/gulp/index.js:35:16)
  at Gulp.<anonymous> (/home/suenot/sites/react-fundamentals/gulp/tasks/watch.coffee:4:8)
  at module.exports (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
  at Gulp.Orchestrator._runTask (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
  at Gulp.Orchestrator._runTask (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/suenot/sites/react-fundamentals/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /home/suenot/.nvm/versions/node/v0.12.0/lib/node_modules/gulp/bin/gulp.js:129:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
  at exports._errnoException (util.js:746:11)
  at FSWatcher.start (fs.js:1176:11)
  at Object.fs.watch (fs.js:1202:11)
  at Gaze._watchDir (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
  at /home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
  at module.exports (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/glob-watcher/index.js:12:17)
  at /home/suenot/sites/react-fundamentals/node_modules/browser-sync/lib/file-watcher.js:19:23
  at forOwn (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/lodash/dist/lodash.js:2105:15)
  at Function.forEach (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/node_modules/lodash/dist/lodash.js:3302:9)
  at module.exports.plugin (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/lib/file-watcher.js:17:7)
  at [object Object].<anonymous> (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/lib/services.js:27:63)
  at [object Object].<anonymous> (/home/suenot/sites/react-fundamentals/node_modules/browser-sync/lib/browser-sync.js:177:28)
  at /home/suenot/sites/react-fundamentals/node_modules/browser-sync/lib/browser-sync.js:191:13
  at Object.asyncCallback [as callback] (dns.js:81:16)
  at Object.onresolve [as oncomplete] (dns.js:201:10)
```

**Comment by sergeylaptev** [comment]
Попробуйте прочитать следующие ресурсы, и отпишитесь о результатах:
https://github.com/gulpjs/gulp/issues/605
https://github.com/gulpjs/gulp/issues/217

**Comment by suenot** [comment]
Спасибо, помог. ;)
https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
